version: '2'

services:

    traefik:
        image: containous/traefik
        command: --web --docker --docker.domain=huitparfait.fr --logLevel=DEBUG
        ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
            - ./acme:/acme

    huitparfait_front:
        build: ./huitparfait-front
        image: huitparfait/huitparfait-front
        labels:
            - "traefik.backend=huitparfait_front"
            - "traefik.protocol=http"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:huitparfait.fr"

    huitparfait-auth:
        build: ./huitparfait-auth
        image: huitparfait/huitparfait-auth
        volumes:
            - ./keys:/jwt-keys
        ports:
            - "127.0.0.1:3000:3000"
        environment:
            NODE_ENV: production
            SERVER_URL: http://localhost:3000
            SERVER_PORT: 3000
            PROXY_URL: http://huitparfait-api
            JWT_PUBLIC_KEY_PATH: /jwt-keys/jwt-public.pem
            JWT_PRIVATE_KEY_PATH: /jwt-keys/jwt-private.pem
            FACEBOOK_CLIENT_ID: FACEBOOK_CLIENT_ID
            FACEBOOK_CLIENT_SECRET: FACEBOOK_CLIENT_SECRET
            GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
            YAHOO_CLIENT_ID: YAHOO_CLIENT_ID
            YAHOO_CLIENT_SECRET: YAHOO_CLIENT_SECRET
        labels:
            - "traefik.backend=huitparfait_front"
            - "traefik.protocol=http"
            - "traefik.port=3000"
            - "traefik.frontend.rule=Host:huitparfait.fr"

    huitparfait_data:
        image: 'neo4j:2.3.3'
        volumes:
            - './huitparfait-data/data:/data'
        ports:
            - '7474:7474'
